# Generated by Django 5.1.1 on 2024-10-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_clientmessage_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmessage',
            old_name='text',
            new_name='message',
        ),
    ]
