# Generated by Django 5.1.1 on 2024-10-28 10:38

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_text_clientmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmessage',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US'),
        ),
    ]
