# Generated by Django 5.1.1 on 2024-11-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='locality',
        ),
    ]
